### ISSUE TITLE
Use Svelte stores for state management

### ISSUE THREAD

**Issue by peterhil** [peterhil/spellbook#41]
Notes:
* Make components represent the state in a **simple view** and not have much logic or state on their own.
* Remember that Svelte store contract is implemented by reactive streams (RXJS/Kefir observervables), but do not overuse Kefir when simpler solutions would work.

Tasks:
- [x] Use store for dropdown state #47 
- [x] Use store for search #63 
- [ ] Use Svelte store for all bookmarks #48 
- [ ] Use derived store for directories #49
